# Generated by Django 4.2.2 on 2023-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=150, verbose_name='Описание')),
                ('pizza_type', models.TextField(choices=[('meat', 'мясная'), ('vegetarian', 'вегетарианская')], verbose_name='Тип')),
                ('dough_type', models.TextField(choices=[('thin', 'тонкое'), ('thick', 'толстое')], verbose_name='Тип теста')),
                ('size', models.IntegerField(choices=[(26, '26'), (30, '30'), (40, '40')], verbose_name='Размер')),
            ],
        ),
    ]
